# Generated by Django 5.0.1 on 2024-03-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('License_plate', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('miles_driven', models.TextField(max_length=15)),
            ],
        ),
    ]
