# Generated by Django 5.0.1 on 2024-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='miles_driven',
            field=models.CharField(max_length=15),
        ),
    ]
