# Generated by Django 5.0.1 on 2024-03-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_alter_vehicle_miles_driven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='miles_driven',
            field=models.IntegerField(max_length=15),
        ),
    ]
